Add accessibility meeting notes for end of 2022 and beginning of 2023
jupyter/accessibility pull request #137
Opened 2023-08-17 04:38 UTC by isabela-pf

I'm adding accessibility meeting notes! There's a lot of notes, so this PR looks big. If it should be broken up instead, let me know.

This PR adds:
- Fixes to the 2022 meeting notes index to make the existing notes appear in the docs (some were not appearing)
- The notes from the end of 2022 to the existing directory and index
- The notes for 2023 up to August 2023 in a new directory

Thanks in advance for the review.

2023-08-24 16:09 UTC, afshin approved these changes
Thank you @isabela-pf!

2023-08-24 16:41 UTC, isabela-pf commented
Thanks for the review! It made me realize I was missing some links to complete the loop.

2023-09-07 16:16 UTC, tonyfast commented
thanks @isabela-pf 

closes #132

2023-09-07 16:39 UTC, isabela-pf commented
I mentioned on this week's accessibility meeting that I plan on self-merging this PR if there's no comment or review otherwise in the next week. As far as I can tell this PR doesn't break anything so it's very iteratable if we find an error later. Thank you!

2023-09-12 16:19 UTC, gabalafou requested changes
I performed the following checks:

- [ ] Dates in the 2022 and 2023 indexes match the files shown in GitHub left sidebar
- [ ] Date in heading and date of filename all match
- [ ] All dates accounted for and in order in headings add to all-minutes.md
- [ ] Scanned the beginning of each agenda looking to see if I spotted any accidental repeats

Marking request changes because I have a couple of questions/suggestions.

2023-09-12 16:19 UTC, gabalafou commented on docs/community/meeting-minutes/jupyterlab-accessibility-meetings/2022/index.md
>  ````{include} 2022-01-26.md
Why does this one still have four back ticks? Shouldn't all the `{include}`s be triple-back-ticked?

2023-09-12 16:19 UTC, gabalafou commented on docs/community/meeting-minutes/jupyterlab-accessibility-meetings/all-minutes.md
> +## May 17, 2023
newline?
```suggestion 

## May 17, 2023
```

2023-09-12 16:40 UTC, merged

2023-09-12 16:40 UTC, tonyfast commented
thanks for this huge amount of work isa!