Add subproject SSC representative term length to documentation
jupyter/accessibility pull request #140
Opened 2023-10-07 03:28 UTC by isabela-pf

Fixes #138

As the Jupyter Accessibility council voted to have a one-year term length for our SSC representative, the result needs to be represented somewhere. I am not aware of any preexisting governance documentation for this project, so I created a page for this purpose. This PR includes

- A new governance page in `governance.md` that briefly outlines our subproject status and the term length we voted on.
- An amendment to the Community section `index.md`'s note that references our status as a subproject. This note now points to `governance.md`

I'll admit I'm not very familiar with Jupyter Book and the docs structure we have now, so I expect to need to update this PR as I find errors. If you catch them before I do, feel free to point them out along with any other review. Thank you in advance!

2023-10-12 15:05 UTC, gabalafou approved these changes
Thanks for updating the docs!

I only caught one small error. Apart from that, I think this good to go.

2023-10-12 15:05 UTC, gabalafou commented on docs/community/governance.md
> +As a Software Subproject, the Jupyter Accessibility council elect one council member to be the project's representative to the [Project Jupyter Software Steering Council (SSC)](https://jupyter.org/go
```suggestion
As a Software Subproject, the Jupyter Accessibility council elects one council member to be the project's representative to the [Project Jupyter Software Steering Council (SSC)](https://jupyter.org/governance/software_steering_council.html).
```

2023-10-12 15:09 UTC, gabalafou requested changes
Oops I spoke too soon. A link needs to be fixed in index.md. Hold on... :)

2023-10-12 15:22 UTC, gabalafou commented on docs/community/index.md
> +Learn more on [our governance documentation]](governance.md)
```suggestion
Learn more on [our governance documentation](governance.md)
```

2023-10-13 06:50 UTC, minrk approved these changes

2023-10-13 08:02 UTC, gabalafou approved these changes
I checked the RTD build. The link works now :)

2023-10-16 17:47 UTC, merged